# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.BooleanField(default=False)),
                ('t', models.BooleanField(default=False)),
                ('w', models.BooleanField(default=False)),
                ('th', models.BooleanField(default=False)),
                ('f', models.BooleanField(default=False)),
                ('s', models.BooleanField(default=False)),
                ('su', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
